[package]
name = "bh" # bo helper
version = "0.1.3"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
tokio = { version = "1.39.2", features = ["full"] }
